# Generated by Django 3.2.6 on 2021-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210827_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dishes',
            field=models.ManyToManyField(to='main_app.Dish'),
        ),
    ]
